FROM python:3.13-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev curl \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir \
    "fastapi" \
    "uvicorn[standard]" \
    "mlflow==3.12.0" \
    "scikit-learn==1.7.2" \
    "xgboost==3.3.0" \
    "numpy==2.5.0" \
    "scipy==1.18.0" \
    "psutil==7.2.2" \
    "pandas" \
    "holidays" \
    "psycopg2-binary" \
    "python-dotenv"

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "src.flightpulse.serve.main:app", "--host", "0.0.0.0", "--port", "8000"]
