FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl build-essential libpq-dev \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    mlflow==3.12.0 \
    psycopg2-binary==2.9.9 \
    boto3

EXPOSE 5000